version: "3.9"
services:

  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./data/db:/var/lib/mysql

  data_layer:
    build:
      context: ./data-layer
      dockerfile: Dockerfile
      args:
        - NODE_ENV={DATA_LAYER_NODE_ENV}
    environment:
      - PORT=3000
      - DB_HOST=${DATABASE_HOST}
      - DB_PORT=${DATABASE_PORT}
      - DB_USER=${DATABASE_USERNAME}
      - DB_PW=${DATABASE_PASSWORD}      
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev


  logic_layer:
    build: .
      ports:
        - "8000:5000"
  redis:
    image: "redis:alpine"

  presentation_layer:
    build: 
      context: ./presentation-layer
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - data_layer